require("dotenv").config()
require("./database/index")
require("./database/syncModels")
const express = require("express")
const cors = require("cors")
const PORT = process.env.PORT
const app = express()
const client=require('./router/clientRoute')
const employee=require('./router/employeeRouter')
const team=require('./router/teamRouter')
const supervisor=require('./router/supervisorRouter')
const request=require('./router/requestRouter')
const notification=require('./router/notification')
const report=require('./router/reportRoute')
const rating=require('./router/ratingRoute')
const admin=require('./router/adminRoute')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded( { extended: true } ))

app.use('/client',client)
app.use('/employee',employee)
app.use('/team',team)
app.use('/notification',notification)
app.use('/rating',rating)
app.use('/admin',admin)
// app.use('/user')
// app.use('/payment')
// app.use('/signup')
// app.use('/login')
// app.use('/category')
app.use('/supervisor',supervisor)
app.use('/request',request)
app.use('/report',report)

app.listen(PORT, () => console.log(`Server is running on port ${PORT}`))