require("dotenv").config()
require("./database/index")
require("./database/syncModels")
const express = require("express")
const cors = require("cors")
const PORT = process.env.PORT
const app = express()
const categoryRoute=require('./router/categoryRoute')
const serviceRoute=require('./router/serviceRoute')
const packRoute=require('./router/packRoute')
const clientRoute=require('./router/clientRoutee')
const packhaserviceRoute=require('./router/packhaserviceRoute')
app.use(cors())
app.use(express.json())
app.use(express.urlencoded( { extended: true } ))

// app.use('/admin')
// app.use('/user')
// app.use('/payment')
// app.use('/signup')
// app.use('/login')
// app.use('/category')
// app.use('/supervisor')
// app.use('request')
// app.use('/report')
app.use('/category',categoryRoute)
app.use('/services',serviceRoute)
app.use('/pack',packRoute)
app.use('/client',clientRoute)
app.use('/packhasservice',packhaserviceRoute)

app.listen(PORT, () => console.log(`Server is running on port ${PORT}`))